---

# Dock applications (in the left section)
configuration_dock_apps:
  - Launchpad
  - Siri
  - Mail
  - Calendar
  - Maps
  - Google Chrome
  - Firefox
  - Safari
#  - PhpStorm
#  - Sublime Text
#  - Slack
  - iTerm
  - App Store
  - System Preferences
#  - Outbank
#  - MeisterTask
#  - Microsoft Word
#  - Microsoft Excel
#  - ScanSnap/ScanSnap Manager


# Dock folders (in the right section)
configuration_dock_folders:
  - ~/Downloads
  - { dest: "{{ system_screenshot_dir }}", view: grid, display: stack, sort: datecreated }