---

- name: Ensure the tap homebrew/php is installed
  homebrew_tap:
    tap: homebrew/php
    state: present


- name: Install PHP version 5.6
  include_tasks: install.yml
  vars:
    version: 5.6

- name: Install PHP version 7.0
  include_tasks: install.yml
  vars:
    version: 7.0

- name: Install PHP version 7.1
  include_tasks: install.yml
  vars:
    version: 7.1