---

- name: Ensure the tap homebrew/php is installed
  homebrew_tap:
    tap: homebrew/php
    state: present


- name: Install PHP version 5.6
  include_tasks: install.yml
  vars:
    version: 5.6
    version_number: 56

- name: Install PHP version 7.0
  include_tasks: install.yml
  vars:
    version: 7.0
    version_number: 70

- name: Install PHP version 7.1
  include_tasks: install.yml
  vars:
    version: 7.1
    version_number: 71


- name: Install composer
  homebrew:
    name: composer
    state: present




