---

# install the dnsmasq package from homebrew
- name: Install dnsmasq with homebrew
  homebrew:
    name: dnsmasq
    state: latest


# create a dev file inside the resolver directory
- name: Add "*.{{ dnsmasq_tld }}" to resolver
  become: yes
  lineinfile:
    state: present
    line: nameserver 127.0.0.1
    create: yes
    dest: /etc/resolver/{{ dnsmasq_tld }}
    owner: root
    group: wheel


# add the *.dev domain in the dnsmasq configuration
- name: Resolve "*.{{ dnsmasq_tld }}" to localhost
  template:
    src: dnsmasq.conf.j2
    dest: /usr/local/etc/dnsmasq.conf