---

# Set the appropriate timezone
timezone: Europe/Berlin

# Set the computer and display sleep times
computer_sleep_time: Never
display_sleep_time: Never

# directory where screenshots are saved to
screenshot_dir: ~/Screenshots